### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by nadako** [hxdefold/hxdefold#1]
I don't have any Photoshop skills, but if this project somehow becomes popular, I think we need a logo for it :-) I have this idea:

take defold logo and replace "plus" with haxe logo shape.

![](http://www.defold.com/static/logos/logo-text-below.png)
![](http://haxe.org/img/haxe-logo.svg)

**Comment by markknol** [comment]
some ideas 

![image](https://cloud.githubusercontent.com/assets/576184/15840800/c3733c0e-2c4c-11e6-9c37-a3f34fc4b87b.png)

**Comment by nadako** [comment]
Thanks a lot, Mark! I think I love these the most:

![](http://i.imgur.com/rDUlHYP.png) ![](http://i.imgur.com/967V7qV.png)

They are simple and I love that they resemble haxe logo shape and have Defold colors at the same time!

**Comment by markknol** [comment]
I refined the edges; here you go. I think the first one is the best because of its rotation. 
This one is transparent.

![Defold Haxe Logo](https://cloud.githubusercontent.com/assets/576184/15848923/f4c9a214-2c8f-11e6-9439-4809c69c7c22.png)
