### ISSUE TITLE
Hot Reload does not work

### ISSUE THREAD

**Issue by insraq** [hxdefold/hxdefold#10]
This is probably due to Lua module reload: https://www.defold.com/manuals/modules/#_hot_reloading_modules

The easiest way is to use a global variable, instead of Lua modules for generated code.

**Comment by nadako** [comment]
Oh, this is gonna be fun. Not only Haxe module returns a local variable, but also the glue scripts do `local script = m.Script.new()`. I'll have to think about this, thanks for reporting!

**Comment by nadako** [comment]
I have an idea, will try something.

**Comment by insraq** [comment]
There's a hack suggested in the official doc:
```
--- module.lua

-- Replace with local M = {} when done
uniquevariable12345 = uniquevariable12345 or {}
local M = uniquevariable12345

M.value = 4711
return M
```
That should work fine. And if the code is generated and we can guarantee that global variable won't have naming conflict, I see no reason not to use this approach.

**Comment by nadako** [comment]
It's a bit more involved than that, but yes, this is the basic approach.
