### ISSUE TITLE
lua libs

### ISSUE THREAD

**Issue by CocosGames** [hxdefold/hxdefold#12]
what to do if i want to use other lua libs in haxe project?

**Comment by nadako** [comment]
That depends on how lazy you are :)

---

The proper way is to write an [extern definition](https://haxe.org/manual/lf-externs.html) for your library. Haxe standard library provides some nice examples of such extern, for example [here](https://github.com/HaxeFoundation/haxe/blob/development/std/lua/lib/luautf8/Utf8.hx) are extern definitions for the `lua-utf8` library.

Note the `@:luaRequire` metadata on the class - that will automatically generate a `require` call. I doesn't seem to be documented in the Haxe manual yet, unfortunately, but it's not rocket science - just try it :) If you don't want to `require` and instead use something that is already present, use `@:native` metadata, like [it's done](https://github.com/hxdefold/hxdefold/blob/02d8820f83b7064137df772c84bbc8df82235811/src/defold/Go.hx#L14) in hxdefold itself.

Another thing that is also used in those definitions is the Lua multiple returns with `@:multiReturn` metadata. This is actually documented in the [manual](https://haxe.org/manual/target-lua-multireturns.html).

---

The lazier way is to go untyped and use `var yourlib:Dynamic = lua.Lua.require("yourlib")` or even `untyped __lua__("some lua syntax")`, but you shouldn't really go this way, unless it's some single one-line usage.

**Comment by CocosGames** [comment]
Many thanks.
