### ISSUE TITLE
Question/Feature Request

### ISSUE THREAD

**Issue by CocosGames** [hxdefold/hxdefold#16]
Is there a way to add ( ) and ; automaticlly at the end of a  function call in VS code?
Thanks.

**Comment by nadako** [comment]
That's a question more for @Gama11 and https://github.com/vshaxe/vshaxe

**Comment by Gama11** [comment]
There isn't really a good way to do that in Haxe, as it you don't always want to _call_ a function when you select it from completion. You might just want to use it as a reference, or call .bind() on it, in which case the auto-insertion would be rather annoying.

However, ( can be used as a commit character to select a function from completion. The ) will then be auto-inserted too if you haven't turned off auto closing braces in VSCode.
