### ISSUE TITLE
How to generic-extend the Script class?

### ISSUE THREAD

**Issue by haath** [hxdefold/hxdefold#18]
Hello, I am trying to create a generic subclass of the `Script` class, but I am getting the following error message:

![image](https://user-images.githubusercontent.com/29335643/68992123-74a75b00-0867-11ea-898a-4a38262c90ae.png)

But the type parameter seems correct to me, since it will just be specified on the classes that then extend this, no?

**Comment by nadako** [comment]
Hi, yeah everything is correct from the Haxe standpoint, it's just the macro that does the magic for scripts doesn't really support intermediate base classes. So it tries to generate defold glue for this and fails since `T` is, well, generic :)
