### ISSUE TITLE
Haxe > 4.0.5 does not generate main.lua (it deletes it!)

### ISSUE THREAD

**Issue by thejustinwalsh** [hxdefold/hxdefold#24]
```
Haxe: 4.1.0
hxdefold: master
OS: Ubuntu Linux 20.04
```
Created a new project in defold, then ran:
`haxelib run hxdefold init`
`haxe build.hxml`

I get a generated script in `scripts/Hello.script` but I do not have a  `main.lua` in the root of the project and building in defold results in the following error:
```
/scripts/Hello.script
	The file '/main.lua' could not be found.
```

_haxe build.hxml --verbose output_:
https://gist.github.com/thejustinwalsh/6e78a41ea731d17378812b69db96e248

**Comment by thejustinwalsh** [comment]
So, I just pulled down https://github.com/hxdefold/hxdefold-example-sidescroller and ran `haxe build.hxml` and the result was git marked main.lua for delete.

I do not see any errors or warnings, or anything else that would lead me to believe that I am doign something wrong, yet not only am I not generating a main.lua file, I am apparently deleting it when building.

**Comment by thejustinwalsh** [comment]
Decided to go on a haxe version quest to determine if that was the culprit.
haxe 4.0.5 is the last working version of haxe that will generate a main.lua file for me.
4.1.0 and 4.1.1 do not generate a main.lua file on Linux or Windows.

**Comment by nadako** [comment]
Yeah, that happens to me too, I think it's some Haxe bug, will investigate...

**Comment by nadako** [comment]
Reported to https://github.com/HaxeFoundation/haxe/issues/9489

**Comment by nadako** [comment]
There's nothing to fix on hxdefold side. As a workaround you can have an empty `main` entry point and change the hxml to have `-main`.

**Comment by thejustinwalsh** [comment]
Adding `-main Main` to the build.hxml and including an empty main as suggested is a suitable workaround for the time being. Thanks!

```hx
class Main {
  public static function main() {
  }
}
```
