### ISSUE TITLE
Release on haxelib through Travis?

### ISSUE THREAD

**Issue by haath** [hxdefold/hxdefold#26]
Is there any interest for the library to be released on [lib.haxe.org](https://lib.haxe.org)?

If so I could make a PR to update `.travis.yml` to automatically push a new version to haxelib whenever there is a tag. For example tag `v1.2.3` would publish version `1.2.3`.

**Comment by nadako** [comment]
Hey. To be honest I don't have a lot of time to maintain this library properly (since I don't use defold and it takes me quite some time to get into the context), but if you're interested in taking over, I can give you push rights :)

**Comment by haath** [comment]
Hey, no worries, that would be great :)

Maybe add me to the group so that I can also update things on the travis side?

Aaand if you'd like to be the primary name for hxdefold on lib.haxe.org you could send me your haxelib password somewhere. Otherwise I could always push it with my account and list you in the maintainers.

**Comment by nadako** [comment]
I've added you to the organization and made a very first release, could you give me your haxelib handle so i can add you to the contributors list in haxelib.json?

**Comment by nadako** [comment]
I'm stupid though, I should've release as an alpha instead of 1.2.164 directly, not exactly sure how to deal with the versioning, given that we want to follow Defold versions but also be able to make extern releases...

**Comment by haath** [comment]
Great :)

It's `Haath`

Then could you please also [encrypt a `HAXELIB_PASSWORD` variable for travis](https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml)?

If you'd rather leave the releases for you to do manually that's fine also, I could ping you when I need you :)

**Comment by haath** [comment]
> I'm stupid though, I should've release as an alpha instead of 1.2.164 directly, not exactly sure how to deal with the versioning, given that we want to follow Defold versions but also be able to make extern releases...

I thiiink haxelib might accept a fourth number.

First release of the `1.2.164` API: `1.2.164.0`
Release on top of `1.2.164` with extra features: `1.2.164.1` and so on.

From [here](https://lib.haxe.org/documentation/creating-a-haxelib-package/) down at **Versioning**.

(but maybe this needs a `beta/alpha/rc` suffix, I haven't tested it)

---

Or the haxelib people could delete/unlist it?

**Comment by haath** [comment]
> I've added you to the organization

I don't have write access to the repo yet fyi

**Comment by haath** [comment]
Hey @nadako, could we get a release push for `1.2.169`?

It will be nice to have because I think `1.2.170` comes with a breaking change. From the [release notes](https://forum.defold.com/t/defold-1-2-170-has-been-released/65631):

```
Another physics fix is that the phyics.raycast() have been updated so that it can return all the raycast hits. 
See the documentation for further info on how this api has changed (it is still backwards compatible though).
```

I assume they made it backwards compatible in Lua by mixing both return types together in a table, and relying on the fact that `ipairs()` ignores non-numeric keys. But for Haxe I think it makes no sense to try to implement such a workaround.

It could be implemented with `EitherType` but if `all=false` also returns a table, then a table would make more sense.

**Comment by nadako** [comment]
Will do later today. And yeah, I think it's fine to only provide the fresh API :)

**Comment by nadako** [comment]
Done, now you can also do releases! \o/

**Comment by haath** [comment]
Great thanks! o7

I will add it to the Travis pipeline then and close the issue.
