### ISSUE TITLE
vectors can be of any dimension, it seems

### ISSUE THREAD

**Issue by nadako** [hxdefold/hxdefold#4]
The `vmath.vector` function can receive a table of any size and make a vector of it. This is used for e.g. animation curves, so we need to express that somehow.

From the `go.animate` doc:

``` lua
    local values = { 0, 0, 0, 0, 0, 0, 0, 0,
                     1, 1, 1, 1, 1, 1, 1, 1,
                     0, 0, 0, 0, 0, 0, 0, 0,
                     1, 1, 1, 1, 1, 1, 1, 1,
                     0, 0, 0, 0, 0, 0, 0, 0,
                     1, 1, 1, 1, 1, 1, 1, 1,
                     0, 0, 0, 0, 0, 0, 0, 0,
                     1, 1, 1, 1, 1, 1, 1, 1 }
     local vec = vmath.vector(values)
```

**Comment by haath** [comment]
This was implemented in [cd0f7594af488e1040c07a50b0c04e5f78780be4](https://github.com/hxdefold/hxdefold/commit/cd0f7594af488e1040c07a50b0c04e5f78780be4).
