### ISSUE TITLE
Why is Hxdefold so far behind? And how can I help?

### ISSUE THREAD

**Issue by HyperAlch** [hxdefold/hxdefold#42]
Hi, I would really love to use `hxdefold` for my project, but it seems to support Defold API `1.6.4` and we are on `1.9.1` currently. How do updates to this library work? Do updates to the supported API version only happen when the Defold API makes a change that requires Haxe definition updates? *(For example, maybe between `1.6.4` and `1.9.1` there are no changes that need to be updated)*

If this is simply a lack of time on your end, what would be the best way to help you out? I assume going through the update notes of every Defold version and making sure there are no API changes that need updating? And if they do need an update, send in a pull request with the updated code?

Thank you for all the time and work you have put into this project!

**Comment by haath** [comment]
Hello, and thanks for the interest!

First just an FYI, targeting a different API version doesn't make it strictly incompatible per se. You can still compile and start working if you just want to experiment with it for example.
The externs will just be out of date, so best case you'll be missing some new function in the Defold API, but worst case some important function (e.g `go.animate`) will have had breaking changes and won't be usable.

To answer your question, yeah it's mainly lack of time. I only play with gamedev on the side as a hobby.

So if you'd like to contribute that would be great :slightly_smiling_face: 
The process is just as you described: I go through the release notes, one version at a time, and implement any changes that I see to the [lua API](https://defold.com/ref/stable/go/).
Obviously, changes that Defold makes to the editor, builtins, engine etc don't affect anything on the Haxe side.

The project is also currently missing a couple of technical things:
* The examples `hxdefold-example-*` under the [org](https://github.com/hxdefold), are all broken and need to be updated to hxdefold v2. (might be a nice way to learn the library and help decide if you like it :wink:)
* The hxdefold repo needs CI. One idea for a testing step would be to clone all example repos once they are all fixed, and make sure that they compile (both with Haxe, and with Defold's bob).
* Our API docs on [github pages](http://hxdefold.github.io/hxdefold/) are terribly outdated. The original author set it up with TravisCI which I don't think is running anymore. We should make a github action for it.
* The project is missing formatting settings (`hxformat.json`).

Let me know if you have any questions!

**Comment by HyperAlch** [comment]
Okay, so here is the plan. I'm going to get some more Haxe experience under my belt as I use the current version of Hxdefold for my own game. I am already very experience with Java, Rust, JavaScript, Golang, etc and have been programming for about 20 years, so the learning process shouldn't be an issue. The progress will more be based on the amount of free time I have.

Once I feel more comfortable with Haxe I'll start going through release notes and update bindings. I feel that keeping up with the Defold API is the most important thing to focus on first. Once we are caught up, to the newest version I'll take a look at the extra stuff you listed and work on those. I will say that I'm not very experienced with Github CL, so that will most likely be the last thing I work on as I will have to invest time into learning it.

**Comment by HyperAlch** [comment]
Separate question. Does `hxdefold` have any way of throwing errors other than a direct untyped lua call?

```
untyped __lua__('_G.error("message here")');
``` 
![image](https://github.com/user-attachments/assets/10d0b4cc-6999-4892-927d-5fdaf64d58fe)

**Comment by HyperAlch** [comment]
@haath @nadako 
**I'm planning on updating hxdefold to the 1.7.0 Defold API version next week**

Have either of you already made progress on this? If so, maybe you could make a separate branch with the things that have already been updated and push it to GitHub so I don't redo work that is already done? If not I'll just go through the release notes ([1.7.0 Release Notes](https://defold.com/2024/03/11/Defold-1-7-0/)) from top to bottom.

I'm hoping to do a Defold API version upgrade every other week until we catch up with the current version.

**Comment by haath** [comment]
@HyperAlch nope, no other work has been done beyond 1.6.4

> If not I'll just go through the release notes ([1.7.0 Release Notes](https://defold.com/2024/03/11/Defold-1-7-0/)) from top to bottom.

sounds good 🙂

**Comment by OscarLeif** [comment]
We have any discord?
I'm writing some missing stuff like 
`physics.set_listener(callback)`
But I'm not sure if what I currently have is fine.
I mean using too much Dynamic in Haxe for the callbacks.

**Comment by haath** [comment]
@OscarLeif there's no discord

If you have some work-in-progress that you'd like feedback on you can always make a draft PR.

We generally try to avoid `Dynamic` completely. After all, types are the advantage that Haxe has over Lua 😉 
Of course there may exist a case where it's unavoidable, you can certainly always start your PR with some `Dynamic` when you can't figure out a better way, and someone else might comment with a suggestion.

**Comment by HyperAlch** [comment]
Hey guys, sorry it has been so long. I've been dealing with a rather large transition in my studio. The small studio I'm apart of brought on 3 Unity guys. A compromise was made and we are actually going to use Godot with C# instead of Defold.

The time given to me to help work on this project has been taken away because the studio would no longer benefit from it. I'm really sorry if I wasted anyones time, and I wish you all the best.
